/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FactureService } from "../facture.service";
import { FactureCreateInput } from "./FactureCreateInput";
import { Facture } from "./Facture";
import { FactureFindManyArgs } from "./FactureFindManyArgs";
import { FactureWhereUniqueInput } from "./FactureWhereUniqueInput";
import { FactureUpdateInput } from "./FactureUpdateInput";

export class FactureControllerBase {
  constructor(protected readonly service: FactureService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Facture })
  async createFacture(
    @common.Body() data: FactureCreateInput
  ): Promise<Facture> {
    return await this.service.createFacture({
      data: {
        ...data,

        vente: data.vente
          ? {
              connect: data.vente,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,
        id: true,
        montantTotale: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Facture] })
  @ApiNestedQuery(FactureFindManyArgs)
  async factures(@common.Req() request: Request): Promise<Facture[]> {
    const args = plainToClass(FactureFindManyArgs, request.query);
    return this.service.factures({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,
        montantTotale: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async facture(
    @common.Param() params: FactureWhereUniqueInput
  ): Promise<Facture | null> {
    const result = await this.service.facture({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,
        montantTotale: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFacture(
    @common.Param() params: FactureWhereUniqueInput,
    @common.Body() data: FactureUpdateInput
  ): Promise<Facture | null> {
    try {
      return await this.service.updateFacture({
        where: params,
        data: {
          ...data,

          vente: data.vente
            ? {
                connect: data.vente,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,
          id: true,
          montantTotale: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFacture(
    @common.Param() params: FactureWhereUniqueInput
  ): Promise<Facture | null> {
    try {
      return await this.service.deleteFacture({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,
          montantTotale: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
