/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Vente } from "./Vente";
import { VenteCountArgs } from "./VenteCountArgs";
import { VenteFindManyArgs } from "./VenteFindManyArgs";
import { VenteFindUniqueArgs } from "./VenteFindUniqueArgs";
import { CreateVenteArgs } from "./CreateVenteArgs";
import { UpdateVenteArgs } from "./UpdateVenteArgs";
import { DeleteVenteArgs } from "./DeleteVenteArgs";
import { FactureFindManyArgs } from "../../facture/base/FactureFindManyArgs";
import { Facture } from "../../facture/base/Facture";
import { Produit } from "../../produit/base/Produit";
import { VenteService } from "../vente.service";
@graphql.Resolver(() => Vente)
export class VenteResolverBase {
  constructor(protected readonly service: VenteService) {}

  async _ventesMeta(
    @graphql.Args() args: VenteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Vente])
  async ventes(@graphql.Args() args: VenteFindManyArgs): Promise<Vente[]> {
    return this.service.ventes(args);
  }

  @graphql.Query(() => Vente, { nullable: true })
  async vente(
    @graphql.Args() args: VenteFindUniqueArgs
  ): Promise<Vente | null> {
    const result = await this.service.vente(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Vente)
  async createVente(@graphql.Args() args: CreateVenteArgs): Promise<Vente> {
    return await this.service.createVente({
      ...args,
      data: {
        ...args.data,

        produit: args.data.produit
          ? {
              connect: args.data.produit,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Vente)
  async updateVente(
    @graphql.Args() args: UpdateVenteArgs
  ): Promise<Vente | null> {
    try {
      return await this.service.updateVente({
        ...args,
        data: {
          ...args.data,

          produit: args.data.produit
            ? {
                connect: args.data.produit,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Vente)
  async deleteVente(
    @graphql.Args() args: DeleteVenteArgs
  ): Promise<Vente | null> {
    try {
      return await this.service.deleteVente(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Facture], { name: "factures" })
  async findFactures(
    @graphql.Parent() parent: Vente,
    @graphql.Args() args: FactureFindManyArgs
  ): Promise<Facture[]> {
    const results = await this.service.findFactures(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Produit, {
    nullable: true,
    name: "produit",
  })
  async getProduit(@graphql.Parent() parent: Vente): Promise<Produit | null> {
    const result = await this.service.getProduit(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
