/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StockListRelationFilter } from "../../stock/base/StockListRelationFilter";
import { VenteListRelationFilter } from "../../vente/base/VenteListRelationFilter";

@InputType()
class ProduitWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nom?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  prix?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  quantit?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => StockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StockListRelationFilter)
  @IsOptional()
  @Field(() => StockListRelationFilter, {
    nullable: true,
  })
  stocks?: StockListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => VenteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VenteListRelationFilter)
  @IsOptional()
  @Field(() => VenteListRelationFilter, {
    nullable: true,
  })
  ventes?: VenteListRelationFilter;
}

export { ProduitWhereInput as ProduitWhereInput };
