/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProduitService } from "../produit.service";
import { ProduitCreateInput } from "./ProduitCreateInput";
import { Produit } from "./Produit";
import { ProduitFindManyArgs } from "./ProduitFindManyArgs";
import { ProduitWhereUniqueInput } from "./ProduitWhereUniqueInput";
import { ProduitUpdateInput } from "./ProduitUpdateInput";
import { StockFindManyArgs } from "../../stock/base/StockFindManyArgs";
import { Stock } from "../../stock/base/Stock";
import { StockWhereUniqueInput } from "../../stock/base/StockWhereUniqueInput";
import { VenteFindManyArgs } from "../../vente/base/VenteFindManyArgs";
import { Vente } from "../../vente/base/Vente";
import { VenteWhereUniqueInput } from "../../vente/base/VenteWhereUniqueInput";

export class ProduitControllerBase {
  constructor(protected readonly service: ProduitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Produit })
  async createProduit(
    @common.Body() data: ProduitCreateInput
  ): Promise<Produit> {
    return await this.service.createProduit({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,
        quantit: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Produit] })
  @ApiNestedQuery(ProduitFindManyArgs)
  async produits(@common.Req() request: Request): Promise<Produit[]> {
    const args = plainToClass(ProduitFindManyArgs, request.query);
    return this.service.produits({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,
        quantit: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async produit(
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Produit | null> {
    const result = await this.service.produit({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        nom: true,
        prix: true,
        quantit: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduit(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() data: ProduitUpdateInput
  ): Promise<Produit | null> {
    try {
      return await this.service.updateProduit({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          nom: true,
          prix: true,
          quantit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduit(
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Produit | null> {
    try {
      return await this.service.deleteProduit({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          nom: true,
          prix: true,
          quantit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/stocks")
  @ApiNestedQuery(StockFindManyArgs)
  async findStocks(
    @common.Req() request: Request,
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Stock[]> {
    const query = plainToClass(StockFindManyArgs, request.query);
    const results = await this.service.findStocks(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,

        produit: {
          select: {
            id: true,
          },
        },

        quantit: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stocks")
  async connectStocks(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        connect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stocks")
  async updateStocks(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        set: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stocks")
  async disconnectStocks(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        disconnect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/ventes")
  @ApiNestedQuery(VenteFindManyArgs)
  async findVentes(
    @common.Req() request: Request,
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Vente[]> {
    const query = plainToClass(VenteFindManyArgs, request.query);
    const results = await this.service.findVentes(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,

        produit: {
          select: {
            id: true,
          },
        },

        quantit: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ventes")
  async connectVentes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: VenteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ventes: {
        connect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ventes")
  async updateVentes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: VenteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ventes: {
        set: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ventes")
  async disconnectVentes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: VenteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ventes: {
        disconnect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
